$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: feature_engineering
display_name: Feature Engineering
version: 1
type: command
inputs:
  input_data:
    type: uri_folder
outputs:
  output_data:
    type: uri_folder
code: ../scripts
environment: azureml:NLP_ML@latest
command: >-
  python feature_engineering.py 
  --input_data ${{inputs.input_data}}
  --output_data ${{outputs.output_data}}
