naive_bayes:
  alpha: 1.0
  fit_prior: True
  random_state: 11

svc:
  C: 1.0
  kernel: 'rbf'
  random_state: 11

logistic_regression:
  penalty: 'l2'
  C: 1.0
  solver: 'lbfgs'
  max_iter: 100
  random_state: 11

random_forest:
  n_estimators: 100
  max_depth: 12
  random_state: 11

gradient_boosting:
  max_leaf_nodes: 128
  min_samples_leaf: 32
  max_depth: 12
  learning_rate: 0.1
  n_estimators: 100
  validation_fraction: 0.1
  random_state: 11

