$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model_svc
display_name: Train Model SVC
version: 1
type: command
inputs:
  train_data: 
    type: uri_folder
  test_data: 
    type: uri_folder
outputs:
  model_output:
    type: mlflow_model
  test_report:
    type: uri_folder
code: .
environment: azureml:NLP_ML@latest
command: >-
  python train_model_svc.py 
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.train_data}}
  --model_output ${{outputs.model_output}}
  --test_report ${{outputs.test_report}}